import type { Control, Sketch } from '../../../src/sketch/types.ts';
import { TABLOID_PAGE } from '../../phase-garden/poster.ts';
import { sloganControls, LETTERING_PEN } from '../../kit/lettering.ts';
import { drawMoon } from './geometry.ts';

const sketch: Sketch = {
  name: 'Breach Tarot: XVIII The Moon',
  page: TABLOID_PAGE,
  pens: [
    { id: 'carbon', color: '#22282c', width: 0.25 },
    { id: 'ultramarine', color: '#3c49aa', width: 0.25 },
    { id: 'vermilion', color: '#d04b3c', width: 0.25 },
    { id: 'acid', color: '#a5a938', width: 0.25 },
    { id: 'violet', color: '#776090', width: 0.25 },
    LETTERING_PEN,
  ],
  controls: [
    { type: 'toggle', id: 'sunlit', label: 'Sunward faces bright (paper), shadow faces hatched', default: true, group: 'Light' },
    { type: 'slider', id: 'nightDeepen', label: 'Night deepened round the moon and the stream (0 none)', default: 1, min: 0, max: 2, step: 0.05, group: 'Light' },
    { type: 'slider', id: 'sunlitEdge', label: 'How far a face must turn to the sun to go to paper', default: 0.02, min: -0.2, max: 0.4, step: 0.01, group: 'Light' },
    { type: 'select', id: 'towerForm', label: 'The towers', default: 'stack', options: ['stack', 'howl'], optionLabels: { stack: 'Two stacks, as approved', howl: 'The howl: the wolf torn toward the moon, the dog staked' }, group: 'Towers' },
    { type: 'slider', id: 'wolfSeat', label: 'Wolf: courses that stay seated', default: 4, min: 2, max: 7, step: 1, group: 'Howl' },
    { type: 'slider', id: 'wolfReach', label: 'Wolf: how far toward the moon its stream reaches', default: 0.88, min: 0.3, max: 0.95, step: 0.01, group: 'Howl' },
    { type: 'slider', id: 'wolfAway', label: 'Wolf: how far back its stream goes (share of its distance)', default: 2, min: 1, max: 3, step: 0.05, group: 'Howl' },
    { type: 'slider', id: 'wolfRise', label: 'Wolf: how long the column rises straight before it leans to the moon', default: 0.7, min: 0.2, max: 1, step: 0.01, group: 'Howl' },
    { type: 'slider', id: 'wolfStream', label: 'Wolf: extra slabs and shards in the stream', default: 16, min: 0, max: 40, step: 1, group: 'Howl' },
    { type: 'slider', id: 'wolfSpread', label: 'Wolf: how far its courses slip to the side as they rise', default: 0.35, min: 0, max: 1.5, step: 0.05, group: 'Howl' },
    { type: 'slider', id: 'wolfGap0', label: 'Wolf: gap between its first loose courses', default: 1.2, min: 0, max: 6, step: 0.1, units: 'mm', group: 'Howl' },
    { type: 'slider', id: 'wolfGap', label: 'Wolf: how much wider the gaps grow toward the top', default: 5, min: 0, max: 30, step: 0.5, units: 'mm', group: 'Howl' },
    { type: 'slider', id: 'wolfShrink', label: 'Wolf: how much smaller the slabs get as they rise', default: 0.5, min: 0, max: 0.8, step: 0.01, group: 'Howl' },
    { type: 'slider', id: 'wolfTumble', label: 'Wolf: how far the slabs turn as they rise', default: 1, min: 0, max: 2.5, step: 0.05, group: 'Howl' },
    { type: 'slider', id: 'dogStrain', label: 'Dog: how far its courses lift against the stakes', default: 0.05, min: 0, max: 0.3, step: 0.01, group: 'Howl' },
    { type: 'slider', id: 'stakeSteep', label: 'Dog: stakes take the volley\'s mean slope (0) or its steepest (1)', default: 1, min: 0, max: 1, step: 0.05, group: 'Howl' },
    { type: 'slider', id: 'stakeSlope', label: 'Dog: stake slope on the sheet (0: the volley\'s)', default: 68, min: 0, max: 80, step: 1, units: '°', group: 'Howl' },
    { type: 'slider', id: 'stakeToward', label: 'Dog: stakes lean toward the eye as they descend', default: -0.5, min: -1, max: 1, step: 0.05, group: 'Howl' },
    { type: 'slider', id: 'stakeShift', label: 'Dog: stakes cross it right of its middle (tower widths)', default: 0.3, min: -0.5, max: 0.5, step: 0.01, group: 'Howl' },
    { type: 'slider', id: 'stakeHigh', label: 'Dog: where the highest stake crosses it (share of its height)', default: 0.7, min: 0.2, max: 0.9, step: 0.01, group: 'Howl' },
    { type: 'slider', id: 'stakeLow', label: 'Dog: where the lowest stake crosses it', default: 0.42, min: 0.05, max: 0.8, step: 0.01, group: 'Howl' },
    { type: 'slider', id: 'stakeReach', label: 'Dog: how far the stakes reach up toward the sky (tower widths)', default: 3, min: 0.8, max: 6, step: 0.1, group: 'Howl' },
    { type: 'slider', id: 'dogKink', label: 'Dog: how far its struck courses kink at the breaks', default: 0.14, min: 0, max: 0.3, step: 0.005, units: 'rad', group: 'Howl' },
    { type: 'slider', id: 'stakes', label: 'Dog: stakes driven through it', default: 3, min: 1, max: 3, step: 1, group: 'Howl' },
    { type: 'slider', id: 'nearTop', label: 'Near tower: top on the sheet', default: 163, min: 120, max: 240, step: 1, units: 'mm', group: 'Towers' },
    { type: 'slider', id: 'nearWidth', label: 'Near tower width (eye heights)', default: 0.62, min: 0.3, max: 1.2, step: 0.01, group: 'Towers' },
    { type: 'slider', id: 'nearX', label: 'Near tower across the card', default: 62, min: 30, max: 120, step: 1, units: 'mm', group: 'Towers' },
    { type: 'slider', id: 'farTop', label: 'Far tower: top on the sheet', default: 189, min: 140, max: 250, step: 1, units: 'mm', group: 'Towers' },
    { type: 'slider', id: 'farWidth', label: 'Far tower width (eye heights)', default: 0.75, min: 0.3, max: 1.2, step: 0.01, group: 'Towers' },
    { type: 'slider', id: 'farX', label: 'Far tower across the card', default: 212, min: 170, max: 245, step: 1, units: 'mm', group: 'Towers' },
    { type: 'slider', id: 'shoreLeft', label: 'Shore at the left edge', default: 330, min: 300, max: 365, step: 1, units: 'mm', group: 'Pool' },
    { type: 'slider', id: 'shoreRight', label: 'Shore at the right edge', default: 286, min: 262, max: 340, step: 1, units: 'mm', group: 'Pool' },
    { type: 'slider', id: 'spit', label: 'Spit of land at the path, reaching toward us', default: 26, min: 0, max: 40, step: 1, units: 'mm', group: 'Pool' },
    { type: 'slider', id: 'ripple', label: 'Ripple in the reflection', default: 0.5, min: 0, max: 2.5, step: 0.05, group: 'Pool' },
    { type: 'slider', id: 'waterPitch', label: 'Water ruling pitch', default: 1.25, min: 0.55, max: 2, step: 0.05, units: 'mm', group: 'Pool' },
    { type: 'slider', id: 'echoFar', label: 'Far tower in the water, as a share of its height', default: 0.55, min: 0.15, max: 1, step: 0.01, group: 'False city' },
    { type: 'slider', id: 'echoNear', label: 'Near tower in the water, as a share of its height', default: 0.3, min: 0.1, max: 1, step: 0.01, group: 'False city' },
    { type: 'slider', id: 'extraX', label: 'Extra tower in the water, across the card', default: 121, min: 70, max: 190, step: 1, units: 'mm', group: 'False city' },
    { type: 'slider', id: 'extraBottom', label: 'Extra tower: where its image ends, down the sheet', default: 381, min: 340, max: 389, step: 1, units: 'mm', group: 'False city' },
    { type: 'slider', id: 'pathX', label: 'Road: where it leaves the water, across the card', default: 150, min: 110, max: 190, step: 1, units: 'mm', group: 'Road' },
    { type: 'slider', id: 'pathVanish', label: 'Road: where it threads out at the horizon', default: 162, min: 110, max: 200, step: 1, units: 'mm', group: 'Road' },
    { type: 'slider', id: 'pathBend', label: 'Road: swing of its S-bends at the water', default: 55, min: 0, max: 140, step: 1, units: 'mm', group: 'Road' },
    { type: 'slider', id: 'pathBends', label: 'Road: how many half-bends', default: 3.5, min: 1.5, max: 6, step: 0.25, group: 'Road' },
    { type: 'slider', id: 'pathWidth', label: 'Road: width where it leaves the water', default: 34, min: 8, max: 70, step: 1, units: 'mm', group: 'Road' },
    { type: 'slider', id: 'pathTwists', label: 'Road: how many times it turns over', default: 3, min: 1, max: 4, step: 1, group: 'Road' },
    { type: 'slider', id: 'pathTwistLength', label: 'Road: length of each turn (share of the road)', default: 0.15, min: 0.03, max: 0.25, step: 0.01, group: 'Road' },
    { type: 'slider', id: 'pathTwistLift', label: 'Road: how far an edge lifts as it turns (half widths)', default: 0.35, min: 0, max: 1, step: 0.05, group: 'Road' },
    { type: 'slider', id: 'pathLift', label: 'Road: height off the ground (half widths)', default: 0.05, min: 0, max: 1, step: 0.01, group: 'Road' },
    { type: 'slider', id: 'pathUnder', label: 'Road: how far it starts under the water (share)', default: 0.08, min: 0, max: 0.3, step: 0.01, group: 'Road' },
    { type: 'slider', id: 'pathEnd', label: 'Road: where it ends on the sheet', default: 252.5, min: 251, max: 270, step: 0.5, units: 'mm', group: 'Road' },
    { type: 'slider', id: 'pathLamination', label: 'Road: closest laminations on the sheet', default: 0.75, min: 0.4, max: 2, step: 0.05, units: 'mm', group: 'Road' },
    { type: 'slider', id: 'pathRibGap', label: 'Road: closest ribs on the sheet', default: 6, min: 0.5, max: 12, step: 0.1, units: 'mm', group: 'Road' },
    { type: 'select', id: 'moonForm', label: 'The moon', default: 'broken', options: ['broken', 'station', 'crescent'], optionLabels: { broken: 'Broken, pierced by slabs', station: 'A station built into a moon', crescent: 'A crescent of slabs' }, group: 'Moon' },
    { type: 'slider', id: 'brokenX', label: 'Broken moon across the card', default: 178, min: 120, max: 240, step: 1, units: 'mm', group: 'Broken moon' },
    { type: 'slider', id: 'brokenY', label: 'Broken moon down the card', default: 108, min: 70, max: 160, step: 1, units: 'mm', group: 'Broken moon' },
    { type: 'slider', id: 'brokenSize', label: 'Broken moon radius', default: 25, min: 15, max: 40, step: 0.5, units: 'mm', group: 'Broken moon' },
    { type: 'slider', id: 'cracks', label: 'Cracks through the rock', default: 4, min: 1, max: 5, step: 1, group: 'Broken moon' },
    { type: 'slider', id: 'brokenGap', label: 'How far the pieces have drifted apart (radii)', default: 0.26, min: 0, max: 0.5, step: 0.01, group: 'Broken moon' },
    { type: 'slider', id: 'brokenTwist', label: 'How far each piece has turned', default: 0.22, min: 0, max: 0.5, step: 0.01, units: 'rad', group: 'Broken moon' },
    { type: 'slider', id: 'piercers', label: 'Slabs driven through it', default: 4, min: 2, max: 6, step: 1, group: 'Broken moon' },
    { type: 'slider', id: 'pierceHeading', label: 'Slabs: the line they are driven along (0 level)', default: 18, min: -90, max: 90, step: 1, units: '°', group: 'Broken moon' },
    { type: 'slider', id: 'pierceAngle', label: 'Slabs: how far each is knocked off that line', default: 0.32, min: 0, max: 0.8, step: 0.01, units: 'rad', group: 'Broken moon' },
    { type: 'slider', id: 'pierceReach', label: 'How far the slabs stand out past the rock (radii)', default: 1, min: 0.3, max: 2.5, step: 0.05, group: 'Broken moon' },
    { type: 'slider', id: 'debris', label: 'Blocks floating round it', default: 14, min: 0, max: 40, step: 1, group: 'Broken moon' },
    { type: 'slider', id: 'debrisSpread', label: 'How far the floating blocks reach (radii)', default: 2.4, min: 1.4, max: 4, step: 0.05, group: 'Broken moon' },
    { type: 'slider', id: 'debrisFloor', label: 'Lowest a floating block may hang on the sheet', default: 176, min: 140, max: 240, step: 1, units: 'mm', group: 'Broken moon' },
    { type: 'slider', id: 'brokenHatch', label: 'Hatch spacing on its blocks (share of the towers\')', default: 1.25, min: 0.8, max: 2.5, step: 0.05, group: 'Broken moon' },
    { type: 'slider', id: 'brokenPitch', label: 'Field line spacing on the sheet', default: 0.75, min: 0.4, max: 1.5, step: 0.01, units: 'mm', group: 'Broken moon' },
    { type: 'slider', id: 'brokenSideAngle', label: 'Ruling on the broken sides seen through the gaps', default: 52, min: -90, max: 90, step: 1, units: '°', group: 'Broken moon' },
    { type: 'slider', id: 'brokenSidePitch', label: 'Broken-side ruling spacing', default: 0.6, min: 0.3, max: 1.5, step: 0.05, units: 'mm', group: 'Broken moon' },
    { type: 'slider', id: 'brokenHalo', label: 'Paper round the broken moon', default: 0.8, min: 0.3, max: 4, step: 0.1, units: 'mm', group: 'Broken moon' },
    { type: 'slider', id: 'stationX', label: 'Station moon across the card', default: 176, min: 120, max: 240, step: 1, units: 'mm', group: 'Station' },
    { type: 'slider', id: 'stationY', label: 'Station moon down the card', default: 128, min: 80, max: 170, step: 1, units: 'mm', group: 'Station' },
    { type: 'slider', id: 'stationSize', label: 'Station moon radius', default: 50, min: 35, max: 65, step: 0.5, units: 'mm', group: 'Station' },
    { type: 'slider', id: 'stationRough', label: 'How far the rock swells off round', default: 0.04, min: 0, max: 0.1, step: 0.005, group: 'Station' },
    { type: 'slider', id: 'spineLean', label: 'Spine: lean across the sheet (0 upright)', default: 52, min: -80, max: 80, step: 1, units: '°', group: 'Station' },
    { type: 'slider', id: 'spineTip', label: 'Spine: far end tipped toward the eye', default: 30, min: -45, max: 60, step: 1, units: '°', group: 'Station' },
    { type: 'slider', id: 'spineTurn', label: 'Spine: turned on its own length', default: 0.45, min: -1.2, max: 1.2, step: 0.01, units: 'rad', group: 'Station' },
    { type: 'slider', id: 'spineWidth', label: 'Spine: width (share of the radius)', default: 0.36, min: 0.12, max: 0.5, step: 0.01, group: 'Station' },
    { type: 'slider', id: 'spineReach', label: 'Spine: how far it stands out past the rock (radii)', default: 1.2, min: 0.2, max: 1.6, step: 0.01, group: 'Station' },
    { type: 'slider', id: 'spineSegments', label: 'Spine: slabs it is built of', default: 6, min: 2, max: 10, step: 1, group: 'Station' },
    { type: 'slider', id: 'collarSize', label: 'Collar size', default: 1, min: 0.6, max: 1.6, step: 0.05, group: 'Station' },
    { type: 'slider', id: 'dock', label: 'Dock ring on the flank (0 none)', default: 1, min: 0, max: 1, step: 1, group: 'Station' },
    { type: 'slider', id: 'scatter', label: 'Small blocks on the lit ground', default: 20, min: 0, max: 60, step: 1, group: 'Station' },
    { type: 'slider', id: 'craters', label: 'Craters on the lit ground', default: 6, min: 0, max: 20, step: 1, group: 'Station' },
    { type: 'slider', id: 'sunSide', label: 'Sun from the side (negative: from the left)', default: -0.85, min: -1.5, max: 1.5, step: 0.05, group: 'Station' },
    { type: 'slider', id: 'sunBehind', label: 'Sun from behind (thins the lit limb)', default: 0, min: -0.5, max: 1.2, step: 0.05, group: 'Station' },
    { type: 'slider', id: 'fieldBow', label: 'Field lines bowed toward the eye', default: 10, min: -40, max: 40, step: 1, units: '°', group: 'Station' },
    { type: 'slider', id: 'rockPitch', label: 'Field line spacing on the sheet', default: 0.62, min: 0.4, max: 1.5, step: 0.01, units: 'mm', group: 'Station' },
    { type: 'slider', id: 'rockMare', label: 'Dark and pale ground on the lit face', default: 0.32, min: 0, max: 0.8, step: 0.01, group: 'Station' },
    { type: 'slider', id: 'collarTone', label: 'Collar and dock tone', default: 0.6, min: 0.2, max: 1.2, step: 0.05, group: 'Station' },
    { type: 'slider', id: 'stationSlack', label: 'Station blocks: hidden-line slack (share of a block\'s least side)', default: 0.3, min: 0.05, max: 1, step: 0.05, group: 'Station' },
    { type: 'slider', id: 'rockClear', label: 'Paper kept round the blocks on the rock', default: 0.45, min: 0.2, max: 2, step: 0.05, units: 'mm', group: 'Station' },
    { type: 'slider', id: 'moonX', label: 'Moon across the card', default: 178, min: 120, max: 245, step: 1, units: 'mm', group: 'Moon' },
    { type: 'slider', id: 'moonY', label: 'Moon down the card', default: 108, min: 55, max: 160, step: 1, units: 'mm', group: 'Moon' },
    { type: 'slider', id: 'moonSize', label: 'Moon radius', default: 50, min: 25, max: 55, step: 0.5, units: 'mm', group: 'Moon' },
    { type: 'slider', id: 'moonPhase', label: 'Crescent thickness (share of the radius)', default: 0.42, min: 0.15, max: 0.7, step: 0.01, group: 'Moon' },
    { type: 'slider', id: 'moonBulge', label: 'Which way the crescent bulges', default: -38, min: -180, max: 180, step: 1, units: '°', group: 'Moon' },
    { type: 'slider', id: 'moonCourses', label: 'Courses of slabs in the crescent', default: 4, min: 1, max: 5, step: 1, group: 'Moon' },
    { type: 'slider', id: 'moonSlabArc', label: 'Longest slab, as an arc of the disc', default: 40, min: 12, max: 60, step: 1, units: '°', group: 'Moon' },
    { type: 'slider', id: 'moonDepth', label: 'Slab depth (share of a course)', default: 1.8, min: 0.5, max: 3, step: 0.05, group: 'Moon' },
    { type: 'slider', id: 'moonTurn', label: 'Moon turned on its upright', default: -0.35, min: -1, max: 1, step: 0.01, units: 'rad', group: 'Moon' },
    { type: 'slider', id: 'moonTip', label: 'Moon tipped back', default: 0.12, min: -0.6, max: 0.6, step: 0.01, units: 'rad', group: 'Moon' },
    { type: 'slider', id: 'moonFront', label: 'Moon light from the front', default: 0.55, min: 0, max: 1.5, step: 0.05, group: 'Moon' },
    { type: 'slider', id: 'moonTone', label: 'Moon slab tone', default: 0.6, min: 0, max: 1, step: 0.05, group: 'Moon' },
    { type: 'slider', id: 'moonHatch', label: 'Moon hatch spacing (kit pitch multiple)', default: 1.1, min: 0.6, max: 4, step: 0.1, group: 'Moon' },
    { type: 'slider', id: 'moonTick', label: 'Shortest moon hatch kept', default: 1.2, min: 0.4, max: 3, step: 0.1, units: 'mm', group: 'Moon' },
    { type: 'slider', id: 'moonGrazing', label: 'Moon faces seen more edge-on than this keep no hatch', default: 0.45, min: 0, max: 0.9, step: 0.05, group: 'Moon' },
    { type: 'slider', id: 'night', label: 'How far the dense night comes down', default: 1, min: 0, max: 1.5, step: 0.05, group: 'Sky' },
    { type: 'slider', id: 'moonHalo', label: 'Paper round the moon', default: 2.6, min: 0.5, max: 6, step: 0.1, units: 'mm', group: 'Moon' },
    { type: 'slider', id: 'hatch', label: 'Tower hatch spacing (kit pitch multiple)', default: 2.2, min: 1, max: 5, step: 0.1, group: 'Towers' },
    { type: 'slider', id: 'knockout', label: 'Paper round what stands', default: 1.1, min: 0.3, max: 3, step: 0.05, units: 'mm', group: 'Towers' },
    { type: 'slider', id: 'slabSlack', label: 'Slab hidden-line slack', default: 0.5, min: 0.1, max: 2, step: 0.05, group: 'Towers' },
    { type: 'slider', id: 'fov', label: 'Field of view', default: 54, min: 36, max: 75, step: 1, units: '°', group: 'Camera' },
    ...sloganControls(1).map((c): Control => c.type === 'text' && c.id === 'slogan' ? { ...c, default: 'none of this light is its own' }
      : c.type === 'slider' && c.id === 'sloganSize' ? { ...c, default: 2.4 } : c),
  ],
  draw(ctx) {
    return drawMoon(ctx);
  },
};

export default sketch;
